

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "DisplaySettings.xaml.h"




void ::WinRT_First_Steps::DisplaySettings::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///DisplaySettings.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///DisplaySettings.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'HeaderBackground'
    HeaderBackground = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HeaderBackground"));
    // Get the ToggleSwitch named 'EnableRevMenu'
    EnableRevMenu = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EnableRevMenu"));
    // Get the ToggleSwitch named 'PascalSyntaxHighlighting'
    PascalSyntaxHighlighting = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PascalSyntaxHighlighting"));
    // Get the ToggleSwitch named 'Boldface'
    Boldface = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Boldface"));
    // Get the Button named 'BoldOn_Button'
    BoldOn_Button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BoldOn_Button"));
    // Get the Button named 'BoldOff_Button'
    BoldOff_Button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BoldOff_Button"));
    // Get the Button named 'RevMenuOn_Button'
    RevMenuOn_Button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"RevMenuOn_Button"));
    // Get the Button named 'RevMenuOff_Button'
    RevMenuOff_Button = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"RevMenuOff_Button"));
}

void ::WinRT_First_Steps::DisplaySettings::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::EnableRevMenuToggled);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::PascalSyntaxHighlightingToggled);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::BoldfaceToggled);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::BoldOn_Click);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::BoldOff_Click);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::RevMenuOn_Click);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::RevMenuOff_Click);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::ResolutionPopup_Big);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::ResolutionPopup_Medium);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::ResolutionPopup_Small);
        break;
    case 11:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::ResolutionPopup_24x80);
        break;
    case 12:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::colorPopup_Amber);
        break;
    case 13:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::colorPopup_Green);
        break;
    case 14:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::colorPopup_Paperwhite);
        break;
    case 15:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::WinRT_First_Steps::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::SettingsBackClicked);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

