

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class AppBar;
                ref class Button;
                ref class StackPanel;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                namespace Primitives {
                    ref class Popup;
                }
            }
        }
    }
}

namespace WinRT_First_Steps
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::AppBar^ appBar;
        private: ::Windows::UI::Xaml::Controls::Button^ ResolutionPopup_Button;
        private: ::Windows::UI::Xaml::Controls::Button^ colorPopup_Button;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ resolutionPopup;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ colorPopup;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ colorPopupPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ resolutionPopupPanel;
    };
}

