

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "DisplaySettings.xaml.h"




void ::ReTro_Pascal::DisplaySettings::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///DisplaySettings.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///DisplaySettings.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Grid named 'HeaderBackground'
    HeaderBackground = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"HeaderBackground"));
    // Get the ToggleSwitch named 'Boldface'
    Boldface = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"Boldface"));
    // Get the ToggleSwitch named 'PascalSyntaxHighlighting'
    PascalSyntaxHighlighting = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"PascalSyntaxHighlighting"));
    // Get the ToggleSwitch named 'EnableRevMenu'
    EnableRevMenu = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"EnableRevMenu"));
    // Get the RadioButton named 'CSAmber'
    CSAmber = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CSAmber"));
    // Get the RadioButton named 'CSGreen'
    CSGreen = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CSGreen"));
    // Get the RadioButton named 'CSWhite'
    CSWhite = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"CSWhite"));
    // Get the RadioButton named 'TSTiny'
    TSTiny = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TSTiny"));
    // Get the RadioButton named 'TSMed'
    TSMed = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TSMed"));
    // Get the RadioButton named 'TSBig'
    TSBig = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TSBig"));
    // Get the RadioButton named 'TSClassic'
    TSClassic = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"TSClassic"));
}

void ::ReTro_Pascal::DisplaySettings::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::BoldfaceToggled);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::PascalSyntaxHighlightingToggled);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(target))->Toggled +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::EnableRevMenuToggled);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::OnSetColorScheme);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::OnSetColorScheme);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::OnSetColorScheme);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::OnSetTerminalSize);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::OnSetTerminalSize);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::OnSetTerminalSize);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(target))->Checked +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::OnSetTerminalSize);
        break;
    case 11:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ReTro_Pascal::DisplaySettings::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&DisplaySettings::SettingsBackClicked);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

