

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class ToggleSwitch;
                ref class RadioButton;
            }
        }
    }
}

namespace ReTro_Pascal
{
    partial ref class DisplaySettings : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ HeaderBackground;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ Boldface;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ PascalSyntaxHighlighting;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ EnableRevMenu;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ CSAmber;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ CSGreen;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ CSWhite;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ TSTiny;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ TSMed;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ TSBig;
        private: ::Windows::UI::Xaml::Controls::RadioButton^ TSClassic;
    };
}

